### ISSUE TITLE
Implement store forward example

### ISSUE THREAD

**Issue by Asitha** [wso2/ballerina-integrator#10]
**Description:**

Write a store forward example in Ballerina based on doc 
https://docs.wso2.com/display/EI650/Storing+and+Forwarding+Messages

**Comment by abeykoon** [comment]
This is `Guaranteed Delivery` pattern. 
In the sample we need to cover

1. Retry to deliver message to the HTTP endpoint for a fixed number of times and give up.

**Comment by abeykoon** [comment]
We may use JMS transactions or CLIENT ACKNOWLEDGE

**Comment by Asitha** [comment]
Are we going to ask the user to write that code? What if we wrap that boilerplate code and create a connector or utility functions and give the option for the user to use that instead?

**Comment by abeykoon** [comment]
@Asitha , yes that's the plan. I was taking about implementation details of the connector to be implemented.

**Comment by abeykoon** [comment]
I have drafted a sample Ballerina program to show how a user would use `jmsStoreClient`. This client is used to store messages on to a JMS Broker. 

This is just to demonstrate the syntax of Store connector. 

```
jmsStore:JmsStoreConfiguration jmsStoreConfig = {
    "InitialContextFactory" : "org.apache.activemq.jndi.ActiveMQInitialContextFactory",
    "ProviderUrl": "tcp://localhost:61616",
    "JNDIQueueName": "myStore",
    "ConnectionFactory" : "QueueConnectionFactory", 
    "UserName": "abc",
    "Password": "abc "
};

//optionally create a failover Store and pass when creating the jmsStoreClient
msStore:Client failoverJmsStore = new(jmsStoreConfig);

//create jmsStoreClient
jmsStore:Client jmsStoreClient = new(jmsStoreConfig, enableGuranteedDelivery = true, failoverStoreClient = failoverJmsStore);

//http --> store message and respond client with 202
service healthcareService on httpListener {
    // HTTP resource listening for messages 
    @http:ResourceConfig { methods: ["POST"], consumes: ["application/json"],
        produces: ["application/json"] }
    resource function make_appointment(http:Caller caller, http:Request request) returns error? {
        
        http:Response response = new;

        // Try parsing the JSON payload from the request
        var payload = request.getJsonPayload();
        if (payload is json) {

            var result = jmsStoreClient->store(payload);
            if(result is error) {
                //hanlde error occured during storing message
                response.statusCode = 500;
                response.setJsonPayload({ "Message": "Error while storing the message on JMS broker" });
                check caller->respond(response);
                return;
            } else {
                //send 202
                response.statusCode = 202;
                check caller->respond(response);
                return;
            }
        } else {
            response.statusCode = 400;
            response.setJsonPayload({ "Message": "Invalid payload - Not a valid JSON payload" });
            check caller->respond(response);
            return;
        }
    }
}

//constructor for Client
type  Client object {
    function __init(jmsStore:JmsStoreConfiguration config, boolen enableGuranteedDelivery = false, StoreClient? storeClient = ()) {

    }
};
```

**Comment by abeykoon** [comment]
And following is the syntax for message processor. It allows the user to plug in a code to handle the response from the backend HTTP client once it forwards the message. 

```
jmsStore:JmsStoreConfiguration jmsStoreConfig = {
    InitialContextFactory : "org.apache.activemq.jndi.ActiveMQInitialContextFactory",
    ProviderUrl: "tcp://localhost:61616",
    JNDIQueueName: "myStore",
    ConnectionFactory : "QueueConnectionFactory", 
    UserName: "abc",
    Password: "abc "
};

jmsStore:JmsForwardingProcessorConfiguration forwardingProcessorConfig = {
StoreConfig: jmsStoreConfig,    
ForwardingInterval:1000,
Cron :"" ,
RetryInterval:1000,
NonRetryHTTPStatusCodes: "200",
MaxRedeliveryAttempts:4,
MaxStoreConnectionAttempts:-1,
StoreConnectionAttemptInterval:1000,
DropMessageOnDeliveryFailure:false,
endpoint : "http://abc.com"
};


public type ForwardingProcessor object {

    //constructor for ForwardingProcessor
    public function __init(JmsForwardingProcessorConfiguration processorConfig, jmsStoreConfig ResponseHandler responseHandler) {
        // handle response
        responseHandler.handleResponse(resp);
    }
};

//abstract object for handling the response 
public type ResponseHandler abstract object {

    public function handleResponse(http:Response resp) returns error?;    
};

//implementation for response handler 
public type ResponseHandlerImpl object {

    *ResponseHandler;

    public function handleResponse(http:Response resp) returns error? {
        // do something to the response
        // return () if success
        // return errror if there is any error

        return ();
    }
};

ResponseHandler responseHandler = new ResponseHandlerImpl();
jmsStore:ForwardingProcessor processor = new(forwardingProcessorConfig, responseHandler);
```

**Comment by abeykoon** [comment]
Let me know if there are comments on the syntax proposed. Also

1. I think `Ballerina Tasks` can be utilized to implement message processor together with `JMS connector`. 
2. JMS connector does not provide resiliency, like retrying if broker went down. The implementations needs to take care about them.

**Comment by abeykoon** [comment]
@IrushiL Could you post the comments received from the review?

**Comment by abeykoon** [comment]
With the discussions it was decided it is better to use a function pointer instead of using an abstract object with a method. 

See the modified sample as below. 

```ballerina
messageStore:messageStoreConfiguration messageStoreConfig = {
    MessageBroker : "ActiveMQ",
    ProviderUrl: "tcp://localhost:61616",
    QueueName: "myStore",
    ConnectionFactory : "QueueConnectionFactory", 
    UserName: "abc",
    Password: "abc "
};

messageStore:JmsForwardingProcessorConfiguration forwardingProcessorConfig = {
    StoreConfig: messageStoreConfig,    
    ForwardingInterval:1000,
    Cron :"" ,
    RetryInterval:1000,
    NonRetryHTTPStatusCodes: [200, 202],
    MaxRedeliveryAttempts:4,
    MaxStoreConnectionAttempts:-1,
    StoreConnectionAttemptInterval:1000,
    DropMessageOnDeliveryFailure:false,
    endpoint : "http://abc.com"
};


//implementation for handling response
function handleResponse(http:Response resp) retruns error? {

}

messageStore:ForwardingProcessor processor = new(forwardingProcessorConfig, handleResponse);
```

The constructor for the message sore will look like below. 

```ballerina
public type ForwardingProcessor object {

    //constructor for ForwardingProcessor
    public function __init(JmsForwardingProcessorConfiguration processorConfig, function (http:Response resp) returns (error?) handleResponse) {
        // handle response in a separate function
        handleResponse.call(resp);
    }
};
```

**Comment by abeykoon** [comment]
Following is the high level design of Message-Store-Forward.

**Highlights**

1. JMS Map message is used for the implementation. All the header names and values will be entries. Payload will be a separate entry with a constant key. 
2. CLIENT ACK is used to ensure guaranteed forwarding of a message to the intended backend. 
3. Resiliency is implemented into the Message store client. 
4.  Resiliency is implemented into the Message processor. 
5. At message processor it will try to reconnect to broker if connection was lost. Polling will be recovered automatically if connection is recovered. 


<img width="1260" alt="Screen Shot 2019-06-28 at 10 15 25 PM" src="https://user-images.githubusercontent.com/4967046/60358383-8ccf2880-99f3-11e9-98ab-750ebb499e01.png">

**Comment by abeykoon** [comment]
This issue is blocked by [1]. 

[1]. https://github.com/ballerina-platform/ballerina-lang/issues/16099

**Comment by abeykoon** [comment]
We need to decide on sensible defaults to the default parameters we pass in.

**Comment by abeykoon** [comment]
Also we need to figure out if we are going to keep message store and processor as one module or two. I would like to have one module and use a name like that denotes both.

**Comment by abeykoon** [comment]
Observability  aspect of message store and processor is not added still to the module.

**Comment by abeykoon** [comment]
Ballerina does not keep the main thread when the task is started. Reported issue [1] to track this. Until we get a fix, it is workaround with a runtime:sleep(x) which user need to use in his main program. 

[1]. https://github.com/ballerina-platform/ballerina-lang/issues/16201

**Comment by abeykoon** [comment]
https://github.com/ballerina-platform/ballerina-lang/issues/16505
