### ISSUE TITLE
Add streaming feature to Kafka connector

### ISSUE THREAD

**Issue by Shakila** [wso2/ballerina-integrator#100]
**Description:**
Introduce new feature to enable streaming capability of Kafka in Ballerina connector.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Shakila** [comment]
We hold this one until we introduce the streaming functionality in Ballerina. As for now, we can achieve the streaming capability with the Kafka consumer as done in the following example [1]. And we can do the transformation once we get the message.

[1] https://github.com/wso2-ballerina/module-kafka/blob/master/samples/ballerina-by-example/examples/kafka_message_consumer_with_tasks/kafka_message_consumer_with_task.bal

**Comment by IrushiL** [comment]
Issue tracked in ballerina-lang https://github.com/ballerina-platform/ballerina-lang/issues/19387.
