### ISSUE TITLE
Create a jenkins job to run tests

### ISSUE THREAD

**Issue by isuruuy429** [wso2/ballerina-integrator#113]
**Description:**
Setup a jenkins job to run all the unit tests.

**Comment by isuruuy429** [comment]
- Setup Pipeline 'dev-ballerina-integrator' in https://jenkins-support-ei.wso2.com/jenkins/

**Comment by Asitha** [comment]
We will need to create a public Jenkins build once the Gradle build is complete #137

**Comment by dinuish94** [comment]
Related PRs:
https://github.com/wso2/ballerina-integrator/pull/327
https://github.com/wso2/ballerina-integrator/pull/323
https://github.com/wso2/ballerina-integrator/pull/320
https://github.com/wso2/ballerina-integrator/pull/319
https://github.com/wso2/ballerina-integrator/pull/306

**Comment by IrushiL** [comment]
Fixed, hence resolving the issue.
