### ISSUE TITLE
Implement ActiveMQ Connector examples

### ISSUE THREAD

**Issue by Asitha** [wso2/ballerina-integrator#14]
**Description:**

Need to verify use cases for connectivity with ActiveMQ broker and write examples as needed for the use cases.
This use cases will cover scenarios such as
- Receiving messages from queue/topic
- Sending messages to queue/topic
- Shared subscription scenario
- JMS based management operations such as  creating temporary topics

**Comment by Asitha** [comment]
@abeykoon Please add the relevant sub-issues under this epic

**Comment by indikasampath2000** [comment]
Sending a message to the ActiveMQ broker written using JMS connector.

https://ei.docs.wso2.com/en/latest/ballerina-integrator/learn/tutorials/messaging-integrations/json-data-to-activemq-queue/1/
