### ISSUE TITLE
[Observability]Create a guide to explain the use of metrics tracing and monitoring. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/ballerina-integrator#183]
**Description:**
Since observability addresses three key areas which are metrics monitoring, tracing and logging, we need to create a guide to explain the use of metrics tracing using Jaeger and logging by setting up an Elastic Stack. 

**Suggested Labels:**
priority/high
severity/normal

**Comment by Maninda** [comment]
Resolved in https://github.com/wso2/ballerina-integrator/pull/326
