### ISSUE TITLE
Create templates for well known EI use cases

### ISSUE THREAD

**Issue by Asitha** [wso2/ballerina-integrator#184]
**Description:**

Need to implement following templates

- [ ] MSMP template
- [x] FTP single instance template
- [ ] FTP scaling template
- [x] JMS template
- [ ] Message Forwarding template
- [x] Salesforce template
- [x] Salesforce bulk api template
- [x] SQS template
- [x] S3 template
- [x] SAP template

**Comment by Asitha** [comment]
Ballerina template support is done in PR https://github.com/ballerina-platform/ballerina-lang/pull/18121

**Comment by IrushiL** [comment]
Reducing the severity level since the high priority use cases are completed.
