### ISSUE TITLE
Migrating FTP Connector to Ballerina 1.0.0

### ISSUE THREAD

**Issue by MalshaL** [wso2/ballerina-integrator#188]
**Description:**
Migration of FTP Module to Ballerina 1.0.0

**Comment by lukinsj** [comment]
I am going to need this as well before we can move to Ballerina 1.0.0

**Comment by MalshaL** [comment]
Resolved with the [PR](https://github.com/wso2-ballerina/module-ftp/pull/57). 
FTP Connector is now available at [Ballerina Central](https://central.ballerina.io/).
See the related Github repo [here](https://github.com/wso2-ballerina/module-ftp).
