### ISSUE TITLE
Templates for ballerina Integrator

### ISSUE THREAD

**Issue by dakshika** [wso2/ballerina-integrator#203]
**Description:**

we need to create $subject for the VSCode extension. please create sub-tasks for each template.

- [X] Hello World
- [ ] Proxying a SOAP API
- [ ] Proxying a REST API
- [x] Content-Based Routing
- [x] Header Based Routing
- [x] Message Filtering
- [x] Protocol switching HTTP to JMS
- [x] Scatter-Gather Flow Control
- [x] File Transfer
- [ ] Guaranteed delivery
- [ ] REST to SOAP
- [ ] Exception Handling
- [x] XML to JSON Transformation
- [ ] Salesforce Leads to Spreadsheet
- [ ] Salesforce Leads to database
- [ ] Export Salesforce Accounts to NetSuite
- [ ] Export Salesforce Account details to Microsoft Dynamics CRM
- [ ] Export Github issues to Google Spreadsheet
  
Additional Areas

- [ ] JSON to XML Mapping
- [ ] RabbitMQ integration
- [x] JMS Integration
- [ ] Database Polling
- [ ] Periodical Schedule Tasks

**Comment by dakshika** [comment]
Some more https://github.com/wso2/ballerina-integrator/issues/184

**Comment by IrushiL** [comment]
Adding to the above list while grouping the templates in align with Ballerina Integrator guides.

**Connectors:**
- [ ] MSMP
- [ ] JMS
- [ ] FTP - Single Instance
- [ ] FTP - Scaling
- [ ] Salesforce
- [ ] Salesforce Bulk
- [ ] SQS
- [ ] S3
- [ ] SAP
- [ ] Kafka
- [ ] Message Forwarding
- [ ] GSheets Salesforce Integration

**Database Integrations:**
- [ ] Data Backend Service
- [ ] Managing Database Transactions

**Integration Patterns:**
- [ ] Backend for Frontend
- [ ] Content Based Routing
- [ ] Header Based Routing
- [ ] Message Construction
- [ ] Message Transformation 
- [ ] XML to JSON Transformation
- [ ] Message Filtering
- [ ] Pass Through Messaging
- [ ] Scatter Gather Messaging

**Messaging:**
- [ ] Asynchronous Messaging
- [ ] Message Broadcasting
- [ ] Messaging with ActiveMQ
- [ ] Messaging with Kafka
- [ ] Messaging with SQS
- [ ] Reliable Delivery 

**Services:**
- [ ] Hello World Service
- [ ] Asynchronous Invocation
- [ ] Parallel Service Orchestration
- [ ] Restful Service
- [ ] Service Composition 
- [ ] Proxying a SOAP API
- [ ] Proxying a REST API
- [ ] REST to SOAP
