### ISSUE TITLE
Verify Kafka Connector for EI use cases

### ISSUE THREAD

**Issue by kasun04** [wso2/ballerina-integrator#23]
- Verify common use cases of Kafka and EI. 
- Verify scalability and load testing.

**Comment by Shakila** [comment]
Please find the comparison doc: https://docs.google.com/document/d/1Gr_b6zQncgYotq8bYn0Lr5vzmu0G8kwlZxDzxVpXNKE/edit?usp=sharing

**Comment by Shakila** [comment]
Now, we are trying to implement the SSL connection.

**Comment by Shakila** [comment]
Please find the progress below:

1. Analyzed other Kafka connector with Ballerina Kafka connector.
2. Filled documentation gaps and added a guide for the samples.
3. Fixed the issues in the samples.
4. Added SSL support to Ballerina Kafka connector.
5. Added the SSL configuration info in the doc.
6. Added samples for consumer and publisher with SSL.
