### ISSUE TITLE
NullPointerException when compiling module 

### ISSUE THREAD

**Issue by indikasampath2000** [wso2/ballerina-integrator#245]
**Description:**
Please refer to https://github.com/ballerina-platform/ballerina-lang/issues/18258

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Asitha** [comment]
Fixed in jBallerina 1.0.0
