### ISSUE TITLE
www/init.sh should be run in the main build

### ISSUE THREAD

**Issue by pramodya1994** [wso2/ballerina-integrator#249]
**Description:**
www/init.sh should be run in the main build to identify site content build errors

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isuruuy429** [comment]
Fixed in https://github.com/wso2/ballerina-integrator/pull/239
