### ISSUE TITLE
Verify web services/SOAP use case

### ISSUE THREAD

**Issue by kasun04** [wso2/ballerina-integrator#28]
- Exposing SOAP services 
- Invoking SOAP services /SOAP Connector

**Comment by Asitha** [comment]
@Maninda I think we need to verify what are the use cases that we have already covered and the gaps.

**Comment by Maninda** [comment]
Ballerina team has [developed a simple client](https://central.ballerina.io/wso2/soap) for SOAP services that can convert an XML message to a SOAP message, add username/password pair as options and call a SOAP endpoint.

### **Remaining Tasks**

1. **Generate a SOAP request on a given WSDL:** This will be like generating a service stub automatically based on the WSDL. This needs a significant level of developer cycles to implement specs.
2. **Exposing a SOAP service:** This is not currently supported by Ballerina language. This has to be implemented possibly on top of existing REST APIs. Then the SOAP compliant security has to be also implemented in Ballerina.
3. **X509 certificate support:** As there is no current implementation in ballerina for X509 certificates, existing JBallerina has to use Java based certificate support. When moving to LLVM, a pure Ballerina implementation would be required.
4. **XSD validation:** Current Ballerina does not support schema validation for SOAP messages though there is an OpenAPI based validation for REST/JSON. It would be required to implement SOAP schema validation in ballerina or wrap the existing Java implementation in JBallerina.

**Comment by Asitha** [comment]
Shall we create separate issues for those subtasks? We will prioritize and tackle them separately.

**Comment by Maninda** [comment]
@Asitha Sure. Will create a set of issues and a related epic.
And there is another task remaining for implementing SOAP protocol.

**MTOM Protocol support for SOAP client:** MTOM is not currently not supported with the SOAP client. It has to be implemented with ballerina.

**Comment by Maninda** [comment]
I have created the epic https://github.com/wso2/ballerina-integrator/issues/60 for fulfilling these requirements.
