### ISSUE TITLE
Implement a guide for IBM MQ 

### ISSUE THREAD

**Issue by Asitha** [wso2/ballerina-integrator#31]
**Description:**

A detailed guide of using IBM MQ as a brokering backend. This should cover details on 
- what are the configurations needs to be done
- receiving and sending messages
- transaction support. If it is same as JMS point to relevant doc
- relevant connectors to be used.
- data transformations if required.

**Comment by KasunAratthanage** [comment]
It is possible to configure the Ballerina JMS connector configurations with IBM WebSphere MQ.

We can use Ballerina jms connector for message-driven processing with IBM WebSphere MQ in a synchronous manner. The Asynchronous Queue Receiver is not consumed JMS messages with IBM WebSphere MQ. Please refer the following link to keep track of this issue.

[wso2/ballerina-integrator#15840](https://github.com/ballerina-platform/ballerina-lang/issues/15840)
