### ISSUE TITLE
Quickstart guide needs some major improvements 

### ISSUE THREAD

**Issue by kasun04** [wso2/ballerina-integrator#314]
Here are some of the key areas that we need to improve wrt to QSG. 

- Installation should be based on Ballerina Integrator installer. Isn't it? 
- Rename "Install Ballerina" to "Installation" or "Before you start" kind of a name.  
- Set up the Editor -> Set up Dev Environment? IDE? 
    - (Remove Tip: No need to mention about other IDEs VS Code is the recommended approach.)
    - We should install EI VS Code editor? 
- The diagram needs to be on the same EI7 theme. 
- Can we explain the basic Ballerina concepts here? Maybe using a diagram followed by concise text? 
- XML -> JSON is a rare use case. So why not implementing JSON -> XML/POX instead? 
- Do we have to pull 'ballerina pull wso2/xml_to_json_transformation' even if we select the use case from the VS Code pallet? 
- Send JSON/XML as embedded content in the curl command. Creating a new file is a pain. 
- No syntax highlighting for Bal code. (???) 

New sections: 
- Quickstart should have Running locally, Docker and K8s sections too. 
- Can we include unit testing as well?

**Comment by samgnaniah** [comment]
Resolving this since we have redone the quick start guide.

https://ei.docs.wso2.com/en/latest/ballerina-integrator/get-started/quick-start-guide/
