### ISSUE TITLE
Update Amazon SQS guide

### ISSUE THREAD

**Issue by pramodya1994** [wso2/ballerina-integrator#345]
**Description:**
Amazon SQS guide located in `docs/content/src/learn/guides/saas-clients/amazonsqs` is not created as a module. Need to create this as a module.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Maninda** [comment]
Completed guide is available in https://github.com/wso2/ballerina-integrator/tree/master/docs/content/src/learn/tutorials/saas-integrations/amazonsqs/notifying-fire-alarm-using-sqs
