### ISSUE TITLE
Update Amazon S3 guide

### ISSUE THREAD

**Issue by pramodya1994** [wso2/ballerina-integrator#346]
**Description:**
Amazon S3 guide located in `docs/content/src/learn/guides/saas-clients/amazons3` is not created as a module. Need to create this as a module.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Nipunich** [comment]
This issue is fixed in https://github.com/wso2/ballerina-integrator/pull/472
