### ISSUE TITLE
Implement File Connector Guide(s)

### ISSUE THREAD

**Issue by Asitha** [wso2/ballerina-integrator#36]
**Description:**

This guide(s) should cover the following use cases
- Retrieving files from a location and doing some message mediation logic
- Sending messages to a file location
- Reading and writing from/to an FTP file source
- Samba support
- FTPS / SFTP support

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by MalshaL** [comment]
Fixed by https://github.com/wso2/ballerina-integrator/pull/324
