### ISSUE TITLE
Fix build warnings in snippet gen code

### ISSUE THREAD

**Issue by Asitha** [wso2/ballerina-integrator#442]
**Description:**

There are warnings related to the EI build on snippet gen part

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by IrushiL** [comment]
Fixed in https://github.com/wso2/ballerina-integrator/pull/447
