### ISSUE TITLE
Ballerina lang does not support return array|error union in inter-op calls

### ISSUE THREAD

**Issue by indikasampath2000** [wso2/ballerina-integrator#459]
**Description:**

The following inter-op call doesn't return a byte[] array.

```
function readBytes(handle message) returns byte[] | error = @java:Method {
    class: "org.wso2.ei.b7a.jms.JmsBytesMessageUtils"
} external;
```

There was a bug in the Ballerina inter-op implementation. As a temporary fix, I have reimplemented it as below.

```
function readBytes(handle message) returns byte[] | error {
    return trap readJavaBytes(message);
}

function readJavaBytes(handle message) returns byte[] = @java:Method {
    class: "org.wso2.ei.b7a.jms.JmsBytesMessageUtils"
} external;
```

It is affecting Java call to return RuntimeException instead of checked exception. We should revert it when Ballerina language fixes the issue.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Asitha** [comment]
Following fixes needs to be reverted once this issue is resolved
- https://github.com/wso2-ballerina/module-storeforward/pull/5
- https://github.com/wso2-ballerina/module-jms/pull/44
