### ISSUE TITLE
Improve Salesforce Connector

### ISSUE THREAD

**Issue by Asitha** [wso2/ballerina-integrator#48]
**Description:**

Need to verify current Salesforce connector and do necessary improvements. Find out relevant integration use cases and fix any feature gaps.

**Comment by ThishaniLucas** [comment]
The current implementation of the connector supports only the handling of various records and queries using the Salesforce Rest API. The records are handled in a more granular manner, i.e different record types (Accounts, Leads, Contacts, etc) are handled under different methods. Should we really need this kind of granularity? If we really need some granularity, should we consider handling Events, Actions, Process Rules, etc, as well, like we have in the ESB connector?  

To improve the connector further, we can consider supporting following.

- Batch data processing by using the Salesforce Bulk API.
- Streaming events in the near real time using the Streaming API.

We can have separate clients to handle each of the main functionalities.

- Records and Queries.
- Batch processing.
- Streaming events.

Also, the only authentication mechanism that's supported is Oauth2. We may need to support other mechanisms such as Basic Auth, JWT, SAML, etc, as well.

@Asitha @abeykoon  - WDYT? Any suggestions?
