### ISSUE TITLE
Implement Amazon S3 Connector

### ISSUE THREAD

**Issue by Asitha** [wso2/ballerina-integrator#49]
**Description:**

Design and implement an Amazon S3 connector.

**Comment by keerthu** [comment]
The existing Amazon S3 connector supports following 7 operations only with mandatory parameters. 
- getBucketList
- createBucket
- getAllObjects
- getObject
- createObject
- deleteObject
- deleteBucket

Need to add support for the optional parameter for these 7 operations and need to implement other operations as well. 

https://github.com/wso2-ballerina/module-amazons3#working-with-amazon-s3-endpoint-actions

**Comment by keerthu** [comment]
Added the API design doc for the base connector AmazonS3Client in https://github.com/wso2-ballerina/module-amazons3/pull/16
