### ISSUE TITLE
Remove SAP guide from the Doc site

### ISSUE THREAD

**Issue by indikasampath2000** [wso2/ballerina-integrator#514]
**Description:**
Please find the doc link - https://ei.docs.wso2.com/en/latest/ballerina-integrator/learn/tutorials/saas-integrations/sap/interacting-with-sap/1/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by samgnaniah** [comment]
Fixed with PR: https://github.com/wso2/ballerina-integrator/pull/517
