### ISSUE TITLE
Change the name of Running as a Java program doc

### ISSUE THREAD

**Issue by Asitha** [wso2/ballerina-integrator#566]
**Description:**

It is better to rename the **Running as a Java Program** doc to **Running on JVM** since this is a JVM based language, not Java. 

Please make sure to update the relevant incoming docs for this as well.

https://ei.docs.wso2.com/en/latest/ballerina-integrator/develop/running-as-a-java-program/

**Comment by samgnaniah** [comment]
Fixed with attached PR.

https://ei.docs.wso2.com/en/latest/ballerina-integrator/develop/running-on-jvm/
