### ISSUE TITLE
QuickStart doc doesn't work

### ISSUE THREAD

**Issue by joaoemilio** [wso2/ballerina-integrator#584]
**Description:**
QuickStart doc doesn't work
https://ei.docs.wso2.com/en/latest/ballerina-integrator/get-started/quick-start-guide/

**Comment by Ibaqu** [comment]
Could you please elaborate? Are there any specific errors being thrown?
Any error logs would be helpful.

**Comment by joaoemilio** [comment]
The error occurs by using Visual Studio code dashboard to create the quickstart project template. 
If you run by using command line it works.

**Comment by joaoemilio** [comment]
by the way, I'd add a command instead of saying to move to the directory of the project, like so:
cd quick-start-guide
