### ISSUE TITLE
[Deploying on Docker] Quick Start guide page not found

### ISSUE THREAD

**Issue by isuruuy429** [wso2/ballerina-integrator#591]
**Description:**
The doc link in [1] does not redirect to the Quick Start Guide page. 

[1] - https://ei.docs.wso2.com/en/latest/ballerina-integrator/develop/deploy-on-docker/

**Suggested Labels:**
priority/medium
severity/low
type/Docs

**Suggested Assignees:**
@samgnaniah

**Comment by samgnaniah** [comment]
Fixed with linked PR.
