### ISSUE TITLE
Redirect link does not work in 'Running your service as a Java program'

### ISSUE THREAD

**Issue by isuruuy429** [wso2/ballerina-integrator#594]
**Description:**
Document: https://ei.docs.wso2.com/en/latest/ballerina-integrator/develop/developing-integration-solution/
Step 3: Build and run the service
The redirect link of 'Running your service as a Java program' has been broken. 

type/Docs

**Suggested Assignees:**
@samgnaniah

**Comment by samgnaniah** [comment]
Fixed with attached PR.
