### ISSUE TITLE
Provide XML validation with XSD

### ISSUE THREAD

**Issue by Asitha** [wso2/ballerina-integrator#61]
**Description:**

Provide support for XML schema validation using XSD.

**Comment by Asitha** [comment]
@kesavany I think we should start with designing the API for this functionality. We have to think in terms of how we expect a Ballerina developer to use this schema validation in their programs and make the API more intuitive for them.

**Comment by Shakila** [comment]
PRs:
https://github.com/wso2-ballerina/module-jsonutils/pull/1
https://github.com/wso2-ballerina/module-xmlutils/pull/1

**Comment by IrushiL** [comment]
Blocking issues are fixing in the following PRs, hence reducing the severity level.

https://github.com/ballerina-platform/ballerina-lang/pull/18572
https://github.com/ballerina-platform/ballerina-lang/pull/18474
https://github.com/ballerina-platform/ballerina-lang/pull/18436
