### ISSUE TITLE
Add support for batch data processing in Salesforce connector

### ISSUE THREAD

**Issue by ThishaniLucas** [wso2/ballerina-integrator#62]
**Description:**
Consume Salesforce Bulk API and introduce jobs and batch data processing.

**Comment by pramodya1994** [comment]
As mentioned in bulk API documentation [1],
For jobs with a contentType of CSV, XML is used as the response format except in the case of bulk query results, which are returned in CSV. 
To ensure that you retrieve responses in JSON, create a job with a contentType of JSON and use JSON for your batch payloads. 
To ensure that you retrieve responses in XML, create a job with a contentType of XML or CSV and use the same format for your batch payloads.
[1] https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/async_api_headers_content_type.htm

**Comment by pramodya1994** [comment]
Blocker in ballerina-lang: https://github.com/ballerina-platform/ballerina-lang/issues/16965

**Comment by pramodya1994** [comment]
Salesforce bulk client can be created as follows using Salesforce client.
```ballerina
import sfdc46;

string epUrl = "https://<REGION>.salesforce.com";

sfdc46:SalesforceConfiguration sfConfig = {
    baseUrl: epUrl,
    clientConfig: {
        accessToken: ACCESS_TOKEN,
        refreshConfig: {
            clientId: CLIENT_ID,
            clientSecret: CLIENT_SECRET,
            refreshToken: REFRESH_TOKEN,
            refreshUrl: "https://login.salesforce.com/services/oauth2/token"
        }
    }
};

// Create salesforce client.
sfdc46:Client sfClient = new(sfConfig);
// Create salesforce bulk client.
sfdc46:SalesforceBulkClient sfBulkClient = sfClient->createSalesforceBulkClient();
```
Following operator clients are available in the Salesforce bulk client.

- CSV
    - CSV insert operator
    - CSV upsert operator
    - CSV update operator
    - CSV delete operator
    - CSV query operator
- JSON
    - JSON insert operator
    - JSON upsert operator
    - JSON update operator
    - JSON delete operator
    - JSON query operator
- XML
    - XML insert operator
    - XML upsert operator
    - XML update operator
    - XML delete operator
    - XML query operator
    
Operator can be created as follows.

```ballerina
// Create bulk JSON uploader object. This will create a job to upload JSON contacts as batches.
sfdc46:JsonInsertOperator | sfdc46:SalesforceError jsonInsertOperator = sfBulkClient->createJsonInsertOperator("Contact");
```
After creating an operator, salesforce job will be created to perform the operation. Then we can add batches to the job 
as follows.

```ballerina
// Contacts to be inserted.
json contacts = [
    {
        description: "Created from Bulk API",
        FirstName: "Morne",
        LastName: "Morkel",
        Title: "SE",
        Phone: "0442226670",
        Email: "morne89@gmail.com",
        My_External_Id__c: "201"
    },
    {
        description: "Created from Bulk API",
        FirstName: "Andi",
        LastName: "Flower",
        Title: "SE",
        Phone: "0442216170",
        Email: "flower.andie@gmail.com",
        My_External_Id__c: "202"
    }
];

// Upload json as a batch.
sfdc46:Batch | sfdc46:SalesforceError batchDetails = jsonInsertOperator->upload(contacts);
```   

Get batch details, batch request details and batch results can be done as follows.
```ballerina
// Get details of first batch.
sfdc46:Batch | sfdc46:SalesforceError batchInfo = jsonInsertOperator->getBatchInfo(BatchID);

// Get batch request details.
json | sfdc46:SalesforceError batchRequestDetails = jsonInsertOperator->getBatchRequest(BatchID);

// Get batch results.
json | sfdc46:SalesforceError batchResults = jsonInsertOperator->getBatchResults(BatchID);
``` 

Get job details, Close or Abort job and get details about all batches of this job can be done as follows.

```ballerina
// Get job details.
sfdc46:Job | sfdc46:SalesforceError jobDetails = jsonInsertOperator->getJobInfo();

// Close the job.
sfdc46:Job | sfdc46:SalesforceError jobClosedDetails = jsonInsertOperator->closeJob();

// Abort the job.
sfdc46:Job | sfdc46:SalesforceError jobAbortDetails = jsonInsertOperator->abortJob();

// Get details about all batches of this job.
sfdc46:BatchInfo | sfdc46:SalesforceError allBatchesInfo = jsonInsertOperator->getAllBatches();
```

**Comment by pramodya1994** [comment]
Fixed in https://github.com/wso2-ballerina/module-salesforce/pull/60
