### ISSUE TITLE
Issues in Backup CSV files using Google Spreadsheets tutorial

### ISSUE THREAD

**Issue by isuruuy429** [wso2/ballerina-integrator#630]
**Description:**
Document: https://ei.docs.wso2.com/en/latest/ballerina-integrator/learn/tutorials/saas-integrations/googlespreadsheet/backup-csv-files-using-googlespreadsheets/1/

1. This document provides steps to create the module from scratch. It needs to have people.csv file inside the resource folder inside the module. Therefore it would be better if we can add a step to insert this file after step 3 rather than mentioning it last. 
Furthermore, it is better to say if the user directly uses the zip file downloaded, the people.csv file can be found at the module/resource folder. 

2. The user is asked to create the module as backup_csv_files. But it is asked to build the module as 'backup-csv-files-using-googlespreadsheets' which is different than the module name in the 'Testing' section. It should be corrected as 

```
ballerina build backup_csv_files
```

**Suggested Labels:**
Priority/normal
type/docs

**Suggested Assignees:**
@samgnaniah

**Comment by dulanjalidilmi** [comment]
We will be refactoring the docs, so issue 1 will be addressed later.
