### ISSUE TITLE
[Managing Database Transactions] Error in sql connector configuration

### ISSUE THREAD

**Issue by isuruuy429** [wso2/ballerina-integrator#640]
**Steps to reproduce:**
1. Navigate to the dashboard through VS code and select the template 'Managing Database Transactions'. 
2. As mentioned in [1], create ballerina.conf file in the root directory and provide database configuration details. 
3. Add lib folder to the root directory and add the mysql-connector jar. (mysql-connector-java-8.0.17.jar)
4. Create the database and relevant tables by running the database script. 
5. Build the module as below. 

> ballerina build --experimental managing_database_transactions

**Expected**: The jar should be created. 
**Actual**: Getting the below error. 

```
 [fail] Error while initializing test suite: {ballerinax/java.jdbc}ApplicationError message=error in sql connector configuration: Failed to get driver instance for jdbcUrl=jdbc:mysql://localhost:3306/bankDB:No suitable driver
        at ballerinax.java_jdbc:createClient(jdbc_client.bal:87)
           ballerinax.java_jdbc.Client:__init(client_endpoint.bal:27)
```

Ballerina.toml
```
[project]
org-name= "isuruuyanage"
version= "0.1.0"

[dependencies]

[platform]
target = "java8"

[[platform.libraries]]
module = "managing_database_transactions"
path = "./lib/mysql-connector-java-8.0.17.jar"
```

ballerina.conf
```
DATABASE_URL = "jdbc:mysql://localhost:3306/bankDB"
DATABASE_USERNAME = "root"
DATABASE_PASSWORD = "root"
```

**Suggested Labels:**
priority/high
severity/major
type/bug

**OS, DB, other environment details and versions:**   
Ballerina Version: 1.0.3 
Tested with following mysql connector versions: 
MacOS: Mojave

- mysql-connector-java-8.0.17.jar
- mysql-connector-java-5.1.44-bin.jar

[1] - https://ei.docs.wso2.com/en/latest/ballerina-integrator/learn/tutorials/database-integrations/managing-database-transactions/1/

**Comment by isuruuy429** [comment]
This project was created through the template and account_manager_test.bal file was created in the tests folder. 
Once the module is built by skipping the tests as below, the executable jar is generated. 

> ballerina build --experimental -a --skip-tests

Therefore this issue seems to happen at the test suite. 
Ballerina Version: 1.0.3

**Comment by dulanjalidilmi** [comment]
This was reproduced in Ballerina 1.0.1 and 1.0.4 as well. Looks like Ballerina.toml file is not referred when running tests. Once I add this driver to <Ballerina_Home>/bre/lib, then i could not reproduce the issue.

**Comment by dulanjalidilmi** [comment]
#### Related issues
https://github.com/ballerina-platform/ballerina-lang/issues/20065
