### ISSUE TITLE
[Reliable Delivery] Message Processor and Message Store are in two templates. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/ballerina-integrator#667]
**Description:**
Document: https://ei.docs.wso2.com/en/latest/ballerina-integrator/learn/tutorials/messaging-integrations/reliable-delivery/1/

Message Store and Message Processor are two different templates. As the zip folder contains both in the same projects we need to be consistent. Since the document explains the whole scenario which needs to be implemented inside one project, it would be better if we can combine these two templates to a single template as Reliable Delivery. 

If not it needs to be specifically mentioned in the document if this scenario is going to be built using templates, it needs to create two projects.  

**Suggested Labels:**
priority/high
severity/major

**Comment by dulanjalidilmi** [comment]
If the user wants to add both modules into the same project, he can create one project and add the other module into the existing project. Isn't it better to maintain 2 separate templates for message store and message processor?

**Comment by dulanjalidilmi** [comment]
Let's update the documentation, stating that we have 2 separate templates for the message processor and message store. User has to create a new project using one template and add the other module to the existing project.
