### ISSUE TITLE
[Messaging with Kafka]Improvements points that can be added to the document 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/ballerina-integrator#669]
**Description:**
Document: https://ei.docs.wso2.com/en/latest/ballerina-integrator/learn/tutorials/messaging-integrations/messaging-with-kafka/1/

1. It has not been asked the user to have the Kafka server installed as a prerequisite. 
2. It is better if we can provide a mechanism on installing this in macOS as the instructions of starting and creating topics are different than mentioned.  

eg: If you install it through homebrew on mac  
`brew install kafka`
Starting Zookeeper
`zookeeper-server-start /usr/local/etc/kafka/zookeeper.properties`

Start Kafka server:
`kafka-server-start /usr/local/etc/kafka/server.properties`

Create a Kafka topic
`kafka-topics --create --topic product-price --zookeeper localhost:2181 --replication-factor 1 --partitions 2`

3. As the module name which is generated from the template is **product_management_system**, it needs to change the module name at the jar building step. 

> ballerina build product_management_system

**Suggested Labels:**
priority/high
severity/major

**Affected Product Version:**
EI 7.0.1
Ballerina 1.0.2

**Comment by dinuish94** [comment]
Added the link to https://kafka.apache.org/quickstart under prerequisites to install Kafka server. The rest of the steps can be continued with that.
