### ISSUE TITLE
[File Integration Using FTP]Improvement points to the doc

### ISSUE THREAD

**Issue by isuruuy429** [wso2/ballerina-integrator#671]
**Description:**
Document: https://ei.docs.wso2.com/en/latest/ballerina-integrator/learn/tutorials/file-based-integrations/file-integration-using-ftp/1/

1. It would be better if we can specifically mention in the doc to create a ballerina.conf file in the root directory and include the configuration details in the following format. Provide how to get the FTP_LISTENER_PATH as well. 
```
FTP_HOST=""
FTP_LISTENER_PORT=21
FTP_USERNAME=""
FTP_PASSWORD=""
FTP_FILE_NAME_PATTERN="(.*).txt"
FTP_LISTENER_PATH=""
FTP_POLLING_INTERVAL=
```

2. It has not asked the user to encrypt the credentials and enter to the ballerina.conf file. 

3. In 'Developing the FTP listener service' section, it has been said as below.  

> The FTP_HOST is the port used to connect with the server, of which the default value is 21

It needs to be corrected as **FTP_LISTENER_PORT** instead of FTP_HOST. 

**Suggested Labels:**
type/docs
priority/high
severity/major

**Comment by dulanjalidilmi** [comment]
Shall we have point 2 in a different section of BI Docs? Maybe, we can create a new section called "BI Best Practices".

**Comment by dulanjalidilmi** [comment]
Created Issue https://github.com/wso2/ballerina-integrator/issues/685
