### ISSUE TITLE
[Working With Salesforce Client]The REST API is not enabled for this Organization

### ISSUE THREAD

**Issue by isuruuy429** [wso2/ballerina-integrator#679]
**Description:**
Document: https://ei.docs.wso2.com/en/latest/ballerina-integrator/learn/tutorials/saas-integrations/sfdc46/working-with-salesforce-client/1/

Once it is trying to send the POST request (Test createAccount resource section in the doc), getting the following output. 
```
the REST API is not enabled for this Organization.
```

As per the Salesforce docs it has been asked to contact Salesforce to request that a connected app be whitelisted to use the REST API[1]. Are we going to add this information to our docs?

[1] - https://developer.salesforce.com/docs/atlas.en-us.packagingGuide.meta/packagingGuide/dev_packages_api_access.htm

**Suggested Labels:**
priority/high
severity/major
type/docs

**Comment by dinuish94** [comment]
We should enable the API access for the user as mentioned in [1].

[1] https://support.geckoboard.com/hc/en-us/articles/217148797-How-do-I-enable-API-access-in-Salesforce-
