### ISSUE TITLE
[Import Contacts into Salesforce Using FTP] It does not get the expected output

### ISSUE THREAD

**Issue by isuruuy429** [wso2/ballerina-integrator#686]
**Description:**
Document: https://ei.docs.wso2.com/en/latest/ballerina-integrator/learn/tutorials/saas-integrations/sfdc46/import-contacts-into-salesforce-using-ftp/1/

**Steps to reproduce:**
1. Follow the steps mentioned in the above doc. 
2. Build the jar
3. Start the service

**Expected**: 
```
2019-09-26 19:14:09,916 INFO  [wso2/salesforce_ftp_integration] - CSV file added to the FTP location: /home/ftp-user/contacts.csv
2019-09-26 19:14:13,855 INFO  [wso2/salesforce_ftp_integration] - Imported contacts successfully!
```

**Actual**:
Only the service gets started and keeps listening to the FTP server. 
```
2019-12-03 12:21:03,735 INFO  [wso2/ftp] - Listening to remote server at 192.168.112.3... 
```

**Suggested Labels:**
priority/high
severity/major

**Comment by dulanjalidilmi** [comment]
Please enable rest API for the salesforce account. This issue occurs during

**Comment by isuruuy429** [comment]
We need to mention this in the docs that which account type that user should create since these are tutorials. It is better if we can mention in the doc about the issue and pointing them to the direct account type.

**Comment by dulanjalidilmi** [comment]
We have updated the documentation with https://github.com/wso2/ballerina-integrator/pull/696.
