### ISSUE TITLE
Implement Amazon SQS Connector

### ISSUE THREAD

**Issue by Asitha** [wso2/ballerina-integrator#69]
**Description:**

Implement Amazon SQS Ballerina connector using the REST API. 

We might need to consider following when designing the API's
- Handling requests for producing and receiving messages
- Handling requests in batches.
- Improving producer and consumer throughput using horizontal scaling

**Comment by Maninda** [comment]
As the first task following API methods were chosen to implement.

1. **createQueue** - Create a new queue in SQS
2. **addToQueue** - Add a message to a created queue
3. **consumeFromQueue** - Consume a message from the queue
4. **deleteFromQueue** - Delete a mesage from queue after consuming from the queue

FIFO queue in SQS was selected to implement first and later Standard queue will be implemented.

**Comment by Maninda** [comment]
Authentication mechanism was implemented for AWS POST requests and the above mentioned API methods were implemented. At the moment the parameters are given as a query parameter string. Ballerina API will be developed for each of the parameters for each of the above API methods.

**Comment by Asitha** [comment]
Can you share a sample ballerina code so that we can see how it looks like at the end? It doesn't have to work, what we are expecting is the API design to get a general understanding.

**Comment by Asitha** [comment]
Done with PR https://github.com/wso2-ballerina/module-amazonsqs/pull/1
