### ISSUE TITLE
[VSCode] [Windows] Project not opening on existing window

### ISSUE THREAD

**Issue by dinuish94** [wso2/ballerina-integrator#703]
**Description:**
When a template is selected and the project is created from the VSCode, it prompts asking whether to open the created project in the existing window or a new window. If the existing window is selected, the project does not open on the existing window.

**Steps to reproduce**
1. Open Ballerina Integrator Dashboard
2. Select a template and click on Create
3. Specify project name, module name, and the location to create the project.
4. Select 'existing window' when it prompts where to open the created project.

**Comment by isuruuy429** [comment]
The created project does not open in a new window as well.
