### ISSUE TITLE
Improve and verify functionality of SAP Connector

### ISSUE THREAD

**Issue by Asitha** [wso2/ballerina-integrator#71]
**Description:**

Need to verify the functionality of the SAP connector and improve the functionality as needed.

**Comment by IrushiL** [comment]
Given below is the proposed API design for Outbound Communication in the Ballerina SAP Connector.

## API Design

* **Sending IDoc Messages:**
```
public remote function sendIdoc(xml idoc, int? idocVersion = 3, boolean? transactions = true) returns string | error = external;
```
* **Sending BAPI Requests:**
```
public remote function sendBapi(xml bapi, boolean? transactions = true) returns string | error = external;
```
* **Sending Queued IDoc Messages:**
```
public remote function sendQueuedIdoc(xml idoc, int? idocVersion = 3, string queueName) returns string | error = external;
```
* **Sending Queued BAPI Requests:**
```
public remote function sendQueuedBapi(xml bapi, string queueName) returns string | error = external;
```

## Use Cases

* **Making Requests Without Transactions:**

**IDoc:**
```
sendIdoc(idoc, idocVersion, false);
```
**BAPI:**
```
sendBapi(bapi, false);
```
* **Enabling Transactions in a Single Request:**

**IDoc:**
```
sendIdoc(idoc, idocVersion, true);
```
**BAPI:**
```
sendBapi(bapi, true);
```
* **Enabling Queued Transactions in a Single Request:**

**IDoc:**
```
sendQueuedIdoc(idoc, idocVersion, queueName);
```
**BAPI:**
```
sendQueuedBapi(bapi, queueName);
```
* **Enabling Transactions for Multiple Requests:** 

_**Note:** Requests should reside inside a Ballerina transaction block for multiple transactions to work._

**IDoc:**
```
sendIdoc(idoc, idocVersion);
```
**BAPI:**
```
sendBapi(bapi);
```
* **Enabling Queued Transactions for Multiple Requests:**

_**Note:** Requests should reside inside a Ballerina transaction block for multiple transactions to work._

**IDoc:**
```
sendQueuedIdoc(idoc, idocVersion, queueName);
```
**BAPI:**
```
sendQueuedBapi(bapi, queueName);
```

**Comment by ThishaniLucas** [comment]
Faced a blocker.
https://github.com/ballerina-platform/ballerina-lang/issues/19271

**Comment by IrushiL** [comment]
Removing the blocker label, since this connector will be kept on hold until the blocker faced in Ballerina is resolved.
