### ISSUE TITLE
[Windows][Enterprise Integrator Documentation JSON to XML and Upload to FTP]Curl command in the doc does not work with Windows

### ISSUE THREAD

**Issue by isuruuy429** [wso2/ballerina-integrator#716]
**Description:**
Doc: https://ei.docs.wso2.com/en/latest/ballerina-integrator/learn/tutorials/integration-patterns-and-soa/converting-json-to-xml-and-upload-to-ftp/1/

**Steps to recreate**
1. Navigate to VS code and create a project in the VSCode dashboard through the template 'JSON to XML Transformation and upload to FTP' in Windows. 
2. Follow the steps in the doc and build the module
3. Run the jar and provide the curl command in the doc which is as below. 

> curl -H "application/json" -d @employees.json http://localhost:8080/company/employees

Expected: The file should be uploaded to FTP and the success message should be displayed. 
Actual: Getting the following error
```
At line:1 char:31
+ curl -H "application/json" -d @employees.json http://localhost:8080/c ...
+                               ~~~~~~~~~~
The splatting operator '@' cannot be used to reference variables in an expression. '@employees' can be used only as an argument to a command. To reference variables in an        
expression use '$employees'.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : SplattingNotPermitted
```

PS: When the service was started in Windows and used the same curl command from a Linux machine, it worked as expected. If the curl command is different in Windows, we need to update the document. 

**Affected Product Version:**
Ballerina Integrator 7.0.1
Ballerina version: 1.0.2

**OS, DB, other environment details and versions:**    
Windows 10

**Comment by dulanjalidilmi** [comment]
Can you list down files from the location you execute the curl command and check whether a file named `employees.json` is located? You can use the `dir` command to list down all files?

**Comment by Sumathi243** [comment]
I tried this sample, am getting following error as response in Postman

{
    "Message": "Error occurred uploading file to FTP.",
    "Resason": "org.wso2.ei.b7a.ftp.core.util.BallerinaFTPException"
}
