### ISSUE TITLE
[Deploying on Kubernetes][Windows]Failure while project is being built

### ISSUE THREAD

**Issue by isuruuy429** [wso2/ballerina-integrator#723]
**Description:**
Doc: https://ei.docs.wso2.com/en/latest/ballerina-integrator/develop/deploy-on-kubernetes/

**Steps to recreate**
1. Create a ballerina project through navigating to Ballerina Dashboard through the 'Quickstart Guide' template. 
2. As specified in the doc, add the Kubernetes configurations. 
3. Build the module. 

Expected: The module should be built. 
Actual: Getting the following error. 

> error [k8s plugin]: module [supun/healthcare_service:0.1.0] unable to connect to server:    Host name may not be null

**Affected Product Version:**
Ballerina Integrator 7.0.1
Ballerina 1.0.2
Docker: 19.03.5
Kubernetes running through Docker desktop.

**OS, DB, other environment details and versions:**    
Windows 10

**Comment by hemikak** [comment]
Please try the following: 

Enable "Expose daemon on tcp://localhost:2375 without TLS" in the windows docker configuration as below:
![docker-localhost-windows](https://user-images.githubusercontent.com/4398820/71880119-9d581c80-3155-11ea-927b-5d5699a56749.png)

Then in the @docker annotation use as follow:
```ballerina
@docker:Config {
    dockerHost: "tcp://localhost:2375"
}
```
