### ISSUE TITLE
Issues with Ballerina and Ballerina Plugin in VSCode

### ISSUE THREAD

**Issue by nadeeshaan** [wso2/ballerina-integrator#746]
**Description:**
Refer https://github.com/ballerina-platform/ballerina-lang/issues/20338

**Comment by IrushiL** [comment]
The issue described in ballerina-platform/ballerina-lang#20338 arises when the ballerina.conf file located inside the project is not configured properly with the configurations of the FTP server. 

Add the FTP server configuration in the ballerina.conf file and retry the sample.
