### ISSUE TITLE
EI Connectors redirect links broken 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/ballerina-integrator#749]
**Description:**
https://ei.docs.wso2.com/en/latest/ballerina-integrator/references/ei-connectors/

Ballerina Central connector links do not seem to work. 
eg: https://central.ballerina.io/wso2/ftp

**Comment by samgnaniah** [comment]
This is an issue on Ballerina Central side. Created an issue:

https://github.com/ballerina-platform/ballerina-lang/issues/20517
