### ISSUE TITLE
Implement service orchestration example

### ISSUE THREAD

**Issue by Asitha** [wso2/ballerina-integrator#9]
**Description:**

Write an example of service orchestration based on doc
https://docs.wso2.com/display/EI650/Exposing+Several+Services+as+a+Single+Service

**Comment by kasun04** [comment]
There's a Ballerina guide already created for this. We need to reuse it.

**Comment by Asitha** [comment]
We are going to use the BBG under guides. This is related to the getting started guide where we skim through the features supported with Ballerina Integrations using the hospital service example.
