### ISSUE TITLE
Add re-connect always feature to Kafka connector

### ISSUE THREAD

**Issue by Shakila** [wso2/ballerina-integrator#92]
**Description:**
Reconnection is there but some number of retries can be done by that. Therefore, we have to add re-connect always feature to the Kafka connector.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Shakila** [comment]
I did a research on introducing this feature. Since the reconnection cannot be handled by the client, we hold this now. Please find the related issue [1].

[1] https://github.com/confluentinc/confluent-kafka-dotnet/issues/725

**Comment by IrushiL** [comment]
This issue is tracked in ballerina-lang https://github.com/ballerina-platform/ballerina-lang/issues/19386.
