### ISSUE TITLE
Website does not show images with relative path

### ISSUE THREAD

**Issue by pramodya1994** [wso2/ballerina-integrator#98]
**Description:**
In the generated Hugo website, images defined with the relative path not showing. 
Need to modify the java code to get the directory path and append it with the given relative path.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Asitha** [comment]
Not relevant.
